drop table Table_0 /*(Accepts_Credit_Cards bool default NULL,business_id charsine*/;
drop table Table_1 /*(Good_for_Kids bool default NULL,business_id charess_id*/;
drop table Table_3 /*(hipster bool default NULL,divey bool default NULL,casual bool default NULL,intimate bool default NULL,classy bool default NULL,touristy bool default NULL,trendy bool default NULL,romantic bool default NULL,business_id chars)*/;
drop table Table_5 /*(lot bool default NULL,validated bool default NULL,street bool default NULL,valet bool default NULL,garage bool default NULL,business_id chars)*/;
drop table nTable_31 /*(brunch bool default NULL,business_id chars)*/;
drop table nnTable_312 /*(Price_Range float, business_id chars)*/;
drop table nnnTable_3123 /*(Take_out bool default NULL,business_id chars)*/;
drop table nnnnTable_31234 /*(Attire char/*(6)*/;
drop table nnnnnTable_312345 /*(Good_For_Groups bool default NULL,business_id chars)*/;
drop table nnnnnnTable_3123456 /*(latenight bool default NULL,business_id chars)*/;
drop table nnnnnnnTable_31234567 /*(breakfast bool default NULL,business_id chars)*/;
drop table Table_13 /*(Noise_Level char*/;
drop table nnnnnnnnTable_312345678 /*(dinner bool default NULL,business_id chars)*/;
drop table nnnnnnnnnTable_3123456789 /*(upscale bool default NULL,business_id chars)*/;
drop table Table_16 /*(Waiter_Service bool default NULL,business_id chars)*/;
drop table nnnnnnnnnnTable_312345678910 /*(dessert bool default NULL,business_id chars)*/;
drop table nTable_00 /*(Takes_Reservations bool default NULL,business_id chars)*/;
drop table nnTable_0012 /*(Delivery bool default NULL,business_id chars)*/;
drop table nnnnnnnnnnnTable_31234567891011 /*(lunch bool default NULL,business_id chars)*/;
drop table Table_20 /*(Wi_Fi char*/;
drop table Table_21 /*(Caters bool default NULL,business_id chars)*/;
drop table nnnnnnnnnnnnTable_3123456789101113 /*(Has_TV bool default NULL,business_id chars)*/;
drop table nnnnnnnnnnnnnTable_312345678910111314 /*(Outdoor_Seating bool default NULL,business_id chars)*/;
drop table Table_23 /*(Alcohol cha)*/;
drop table Table_24 /*(Dogs_Allowed bool default NULL,business_id chars)*/;
drop table Table_25 /*(Wheelchair_Accessible bool default NULL,business_id chars)*/;
drop table Table_26 /*(Drive_Thru bool default NULL,business_id chars)*/;
drop table Table_27 /*(By_Appointment_Only bool default NULL,business_id chars)*/;
drop table Table_28 /*(Smoking char/)*/;
drop table Table_29 /*(Good_For_Dancing bool default NULL,business_id chars)*/;
drop table Table_30 /*(Happy_Hour bool default NULL,business_id chars)*/;
drop table Table_31 /*(Coat_Check bool default NULL,business_id chars)*/;
drop table Table_32 /*(background_music bool default NULL,business_id chars)*/;
drop table Table_33 /*(live bool default NULL,business_id chars)*/;
drop table Table_34 /*(karaoke bool default NULL,business_id chars)*/;
drop table Table_35 /*(video bool default NULL,business_id chars)*/;
drop table Table_36 /*(jukebox bool default NULL,business_id chars)*/;
drop table Table_37 /*(dj bool default NULL,business_id chars)*/;
drop table Table_38 /*(Accepts_Insurance bool default NULL,business_id chars)*/;
drop table Table_39 /*(Corkage bool default NULL,business_id chars)*/;
drop table Table_40 /*(BYOB bool default NULL,business_id chars)*/;
drop table Table_41 /*(BYOBCorkage char/*(11)*/;
drop table Table_42 /*(Order_at_Counter bool default NULL,business_id chars)*/;
drop table Table_43 /*(Open_24_Hours bool default NULL,business_id chars)*/;
drop table Table_44 /*(Ages_Allowed char/*(*/;
drop table Table_45 /*(kosher bool default NULL,gluten_free bool default NULL,halal bool default NULL,vegetarian bool default NULL,dairy_free bool default NULL,soy_free bool default NULL,vegan bool default NULL,business_id chars)*/;
