using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Collections;

namespace parse_yelp
{
    
    /* The list of the main categories. All other categories that appear in the business objects are considered sub-categories. */
    class Categories
    {
        public String[] mainCategories = new String[28];
        private Hashtable tmp = new Hashtable();
        private List<string> subCat;
        //private string key;
        public List<string> allCc;
        public Categories()
        {

            mainCategories[0] =  "Active Life";
            mainCategories[1] =  "Arts & Entertainment";    
            mainCategories[2] =  "Automotive";
            mainCategories[3] =  "Car Rental";
            mainCategories[4] =  "Cafes";
            mainCategories[5] =  "Beauty & Spas";
            mainCategories[6] =  "Convenience Stores";
            mainCategories[7] =  "Dentists";
            mainCategories[8] =  "Doctors";
            mainCategories[9] =  "Drugstores";
            mainCategories[10] =  "Department Stores";
            mainCategories[11] =  "Education";
            mainCategories[12] =  "Event Planning & Services";
            mainCategories[13] =  "Flowers & Gifts";
            mainCategories[14] =  "Food";
            mainCategories[15] =  "Health & Medical";
            mainCategories[16] =  "Home Services";
            mainCategories[17] =  "Home & Garden";
            mainCategories[18] =  "Hospitals";
            mainCategories[19] =  "Hotels & Travel";
            mainCategories[20] =  "Hardware Stores";
            mainCategories[21] =  "Grocery";
            mainCategories[22] =  "Medical Centers";
            mainCategories[23] =  "Nurseries & Gardening";
            mainCategories[24] =  "Nightlife";
            mainCategories[25] =  "Restaurants";
            mainCategories[26] =  "Shopping";
            mainCategories[27] =  "Transportation";

            subCat = allSubCats.Split(',').ToList<string>();
            allCc=allC.Split(',').ToList<string>();

            //key = "";

            //foreach(string s in subCat)
            //{
            //    //Console.WriteLine(s);
            //    string t = SuperClean(s);
                
            //    if (this.cExists(t))
            //    {
                    
            //        if(!tmp.ContainsKey(ParseJSONObjects.repSpac2Und(t)))
            //        {
            //            tmp.Add(ParseJSONObjects.repSpac2Und(t), new List<string>());
            //        }

            //        key = ParseJSONObjects.repSpac2Und(t);

            //    }

            //    else
            //    {
                    
            //        (tmp[key] as List<string>).Add(ParseJSONObjects.repSpac2Und(t));
            //    }

                
            //}

        }

        private string SuperClean(string inStr)
        {
            string t = ParseJSONObjects.cleanTextforSQL(inStr);
            string s = "";

            foreach(char x in t)
            {
                if(x !='?')
                {
                    s += x;
                }

            }

            return s;
        }

        public int cLength()
        {
            return mainCategories.Length;
        }

        public bool cExists(string bCategory)
        {
            return mainCategories.Contains(bCategory);
                                  
        }

        public Hashtable getAll
        {
            get
            {
                return tmp;
            }
        }

        public List<string> getAllCc
        {
            get
            {
                return allCc;
            }
        }

        private string allC = "Fast_Food,Restaurants,Bars,American__New,Nightlife,Lounges,American__Traditional,Burgers,Breakfast_and_Brunch,Food,Grocery,Sandwiches,Cafes,Local_Services,Sewing_and_Alterations,Italian,Pizza,Coffee_and_Tea,Chinese,Gluten_Free,Diners,Department_Stores,Fashion,Shopping,Seafood,Bakeries,Desserts,Japanese,Beer__Wine_and_Spirits,Drugstores,Sports_Bars,Barbeque,Health_and_Medical,Chiropractors,Hardware_Stores,Nurseries_and_Gardening,Appliances,Home_and_Garden,Specialty_Food,Mediterranean,Wine_Bars,Vegetarian,Ice_Cream_and_Frozen_Yogurt,Pubs,Delis,Hot_Dogs,Sushi_Bars,Hotels_and_Travel,Pediatric_Dentists,Dentists,General_Dentistry,Cosmetic_Dentists,Indian,Security_Systems,Home_Services,Mexican,Tex_Mex,Bagels,Salad,Greek,Middle_Eastern,Steakhouses,Korean,Shoe_Repair,Thai,Vietnamese,Optometrists,Eyewear_and_Opticians,Convenience_Stores,Carpet_Installation,Carpet_Cleaning,Doctors,Pediatricians,Family_Practice,Southern,French,Cajun_Creole,Mobile_Phones,Shipping_Centers,Notaries,Printing_Services,Pakistani,Obstetricians_and_Gynecologists,Television_Service_Providers,Electronics_Repair,Pest_Control,Movers,Self_Storage,Juice_Bars_and_Smoothies,Buffets,Garage_Door_Services,Medical_Centers,Orthodontists,Musical_Instrument_Services,Guitar_Stores,Taxis,Airport_Shuttles,Transportation,Urgent_Care,Shades_and_Blinds,Ethnic_Food,Dermatologists,Blood_and_Plasma_Donation_Centers,Hawaiian,Child_Care_and_Day_Care,Fireplace_Services,Recycling_Center,Pool_Cleaners,Water_Delivery,Vegan,Windows_Installation,Glass_and_Mirrors,Furniture_Reupholstery,Paint_Stores,Wigs,Uniforms,Physical_Therapy,Vitamins_and_Supplements,Pawn_Shops,High_Fidelity_Audio_Equipment,Home_Theatre_Installation,Solar_Installation,Interior_Design,Flooring,Home_Inspectors,Door_Sales_Installation,Screen_Printing,Screen_Printing_T_Shirt_Printing,Home_Organization,Hospitals,Weight_Loss_Centers,Massage_Therapy,Filipino,Trophy_Shops,Christmas_Trees,Hungarian,Gastropubs,Damage_Restoration,Tours,Latin_American,Pasta_Shops,Fish_and_Chips,Tree_Services,Arts_and_Crafts,Embroidery_and_Crochet,Head_Shops,Popcorn_Shops,Bespoke_Clothing,Brewing_Supplies,Supper_Clubs,Adult,Piano_Stores,Guns_and_Ammo,Fences_and_Gates,Metal_Fabricators,British,Bail_Bondsmen,Automotive,Auto_Glass_Services,Powder_Coating,Jewelry_Repair,Watch_Repair,Leather_Goods,Battery_Stores,Irish_Pub,Mailbox_Centers,Roofing,Shutters,Pool_and_Hot_Tub_Service,Sleep_Specialists,Engraving,Food_Stands,Utilities,Coffeeshops,Cupcakes,Organic_Stores,Macarons,Empanadas,Water_Purification_Services,Furniture_Repair,Diagnostic_Services,Home_Window_Tinting,Swimwear,Window_Washing,Chimney_Sweeps,Teppanyaki,Pool_and_Billiards,Junk_Removal_and_Hauling,Auto_Detailing,Pub_Food,Farming_Equipment,Handyman,Vape_Shops,Auto_Customization,Food_Trucks,Landscape_Architects,Airport_Lounges,Windshield_Installation_and_Repair,Pressure_Washers,Irrigation,Colonics,Home_Automation,Formal_Wear,Livestock_Feed_and_Supply,Horse_Equipment_Shops,Maternity_Wear,Wheel_and_Rim_Repair,Car_Rental,Pumpkin_Patches,Vehicle_Shipping,Customized_Merchandise,Beer_Gardens,Hats,Gutter_Services,Lice_Services,Chicken_Shop,Auction_Houses,Cooking_Classes,Golf_Equipment_Shops,Gold_Buyers";
        private string allSubCats = @"Active Life,active,
ATV Rentals/Tours,atvrentals,
Amateur Sports Teams,amateursportsteams,
Amusement Parks,amusementparks,
Aquariums,aquariums,
Archery,archery,
Badminton,badminton,
Baseball Fields,baseballfields,
Basketball Courts,basketballcourts,
Batting Cages,battingcages,
Beaches,beaches,
Bike Rentals,bikerentals,
Boating,boating,
Bowling,bowling,
Carousels,carousels,
Challenge Courses,challengecourses,
Climbing,climbing,
Cycling Classes,cyclingclasses,
Day Camps,daycamps,
Disc Golf,discgolf,
Diving,diving,
Free Diving,freediving,
Scuba Diving,scuba,
Escape Games,escapegames,
Fencing Clubs,fencing,
Fishing,fishing,
Fitness & Instruction,fitness,
Barre Classes,barreclasses,
Boot Camps,bootcamps,
Boxing,boxing,
Cardio Classes,cardioclasses,
Dance Studios,dancestudio,
Golf Lessons,golflessons,
Gyms,gyms,
Martial Arts,martialarts,
Meditation Centers,meditationcenters,
Pilates,pilates,
Qi Gong,qigong,
Swimming Lessons/Schools,swimminglessons,
Tai Chi,taichi,
Trainers,healthtrainers,
Yoga,yoga,
Flyboarding,flyboarding,
Go Karts,gokarts,
Golf,golf,
Gun/Rifle Ranges,gun_ranges,
Gymnastics,gymnastics,
Hang Gliding,hanggliding,
Hiking,hiking,
Horse Racing,horseracing,
Horseback Riding,horsebackriding,
Hot Air Balloons,hot_air_balloons,
Jet Skis,jetskis,
Kids Activities,kids_activities,
Kiteboarding,kiteboarding,
Lakes,lakes,
Laser Tag,lasertag,
Leisure Centers,leisure_centers,
Mini Golf,mini_golf,
Mountain Biking,mountainbiking,
Paddleboarding,paddleboarding,
Paintball,paintball,
Parks,parks,
Dog Parks,dog_parks,
Skate Parks,skate_parks,
Playgrounds,playgrounds,
Races & Competitions,races,
Rafting/Kayaking,rafting,
Recreation Centers,recreation,
Rock Climbing,rock_climbing,
Skating Rinks,skatingrinks,
Skydiving,skydiving,
Sledding,sledding,
Snorkeling,snorkeling,
Soccer,football,
Sports Clubs,sports_clubs,
Squash,squash,
Summer Camps,summer_camps,
Surfing,surfing,
Swimming Pools,swimmingpools,
Tennis,tennis,
Trampoline Parks,trampoline,
Tubing,tubing,
Water Parks,waterparks,
Wildlife Hunting Ranges,wildlifehunting,
Ziplining,zipline,
Zoos,zoos,
Arts & Entertainment,arts,
Arcades,arcades,
Art Galleries,galleries,
Bingo Halls,bingo,
Botanical Gardens,gardens,
Cabaret,cabaret,
Casinos,casinos,
Cinema,movietheaters,
Country Clubs,countryclubs,
Cultural Center,culturalcenter,
Farms,farms,
Attraction Farms,attractionfarms,
Pick Your Own Farms,pickyourown,
Ranches,ranches,
Festivals,festivals,
Haunted Houses,hauntedhouses,
Jazz & Blues,jazzandblues,
LAN Centers,lancenters,
Museums,museums,
Music Venues,musicvenues,
Observatories,observatories,
Opera & Ballet,opera,
Paint & Sip,paintandsip,
Performing Arts,theater,
Planetarium,planetarium,
Professional Sports Teams,sportsteams,
Psychics & Astrologers,psychic_astrology,
Race Tracks,racetracks,
Social Clubs,social_clubs,
Stadiums & Arenas,stadiumsarenas,
Ticket Sales,ticketsales,
Wineries,wineries,
Wine Tasting Room,winetastingroom,
Automotive,auto,
Aircraft Dealers,aircraftdealers,
Auto Customization,autocustomization,
Auto Detailing,auto_detailing,
Auto Glass Services,autoglass,
Auto Loan Providers,autoloanproviders,
Auto Parts & Supplies,autopartssupplies,
Auto Repair,autorepair,
Auto Upholstery,autoupholstery,
Boat Dealers,boatdealers,
Body Shops,bodyshops,
Car Brokers,carbrokers,
Car Buyers,carbuyers,
Car Dealers,car_dealers,
Car Share Services,carshares,
Car Stereo Installation,stereo_installation,
Car Wash,carwash,
Commercial Truck Dealers,truckdealers,
Commercial Truck Repair,truckrepair,
Fuel Docks,fueldocks,
Gas & Service Stations,servicestations,
Marinas,marinas,
Mobile Dent Repair,mobiledentrepair,
Mobility Equipment Sales & Services,mobilityequipment,
Motorcycle Dealers,motorcycledealers,
Motorcycle Repair,motorcyclerepair,
Motorsport Vehicle Dealers,motodealers,
Motorsport Vehicle Repairs,motorepairs,
Oil Change Stations,oilchange,
Parking,parking,
RV Dealers,rv_dealers,
RV Repair,rvrepair,
Registration Services,registrationservices,
Roadside Assistance,roadsideassist,
Smog Check Stations,smog_check_stations,
Tires,tires,
Towing,towing,
Trailer Dealers,trailerdealers,
Trailer Repair,trailerrepair,
Transmission Repair,transmissionrepair,
Truck Rental,truck_rental,
Vehicle Shipping,vehicleshipping,
Vehicle Wraps,vehiclewraps,
Wheel & Rim Repair,wheelrimrepair,
Windshield Installation & Repair,windshieldinstallrepair,
Beauty & Spas,beautysvc,
Barbers,barbers,
Cosmetics & Beauty Supply,cosmetics,
Day Spas,spas,
Eyelash Service,eyelashservice,
Hair Extensions,hair_extensions,
Hair Loss Centers,hairloss,
Hair Removal,hairremoval,
Laser Hair Removal,laser_hair_removal,
Sugaring,sugaring,
Threading Services,threadingservices,
Waxing,waxing,
Hair Salons,hair,
Blow Dry/Out Services,blowoutservices,
Hair Extensions,hair_extensions,
Hair Stylists,hairstylists,
Men's Hair Salons,menshair,
Makeup Artists,makeupartists,
Massage,massage,
Medical Spas,medicalspa,
Nail Salons,othersalons,
Nail Technicians,nailtechnicians,
Permanent Makeup,permanentmakeup,
Piercing,piercing,
Rolfing,rolfing,
Skin Care,skincare,
Tanning,tanning,
Spray Tanning,spraytanning,
Tanning Beds,tanningbeds,
Tattoo,tattoo,
Teeth Whitening,teethwhitening,
Education,education,
Adult Education,adultedu,
Art Classes,artclasses,
College Counseling,collegecounseling,
Colleges & Universities,collegeuniv,
Educational Services,educationservices,
Elementary Schools,elementaryschools,
Middle Schools & High Schools,highschools,
Preschools,preschools,
Private Tutors,privatetutors,
Religious Schools,religiousschools,
Special Education,specialed,
Specialty Schools,specialtyschools,
Art Schools,artschools,
Bartending Schools,bartendingschools,
CPR Classes,cprclasses,
Childbirth Education,childbirthedu,
Cooking Schools,cookingschools,
Cosmetology Schools,cosmetology_schools,
Dance Schools,dance_schools,
Driving Schools,driving_schools,
Firearm Training,firearmtraining,
First Aid Classes,firstaidclasses,
Flight Instruction,flightinstruction,
Food Safety Training,foodsafety,
Language Schools,language_schools,
Massage Schools,massage_schools,
Nursing Schools,nursingschools,
Parenting Classes,parentingclasses,
Pole Dancing Classes,poledancingclasses,
Ski Schools,skischools,
Swimming Lessons/Schools,swimminglessons,
Vocational & Technical School,vocation,
Tasting Classes,tastingclasses,
Cheese Tasting Classes,cheesetastingclasses,
Wine Tasting Classes,winetasteclasses,
Test Preparation,testprep,
Tutoring Centers,tutoring,
Event Planning & Services,eventservices,
Bartenders,bartenders,
Boat Charters,boatcharters,
Cards & Stationery,stationery,
Caricatures,caricatures,
Caterers,catering,
Clowns,clowns,
DJs,djs,
Face Painting,facepainting,
Game Truck Rental,gametruckrental,
Golf Cart Rentals,golfcartrentals,
Henna Artists,hennaartists,
Hotels,hotels,
Mountain Huts,mountainhuts,
Rest Stops,reststops,
Magicians,magicians,
Mohels,mohels,
Musicians,musicians,
Officiants,officiants,
Party & Event Planning,eventplanning,
Party Bike Rentals,partybikerentals,
Party Bus Rentals,partybusrentals,
Party Characters,partycharacters,
Party Equipment Rentals,partyequipmentrentals,
Party Supplies,partysupplies,
Personal Chefs,personalchefs,
Photo Booth Rentals,photoboothrentals,
Photographers,photographers,
Event Photography,eventphotography,
Session Photography,sessionphotography,
Trivia Hosts,triviahosts,
Valet Services,valetservices,
Venues & Event Spaces,venues,
Videographers,videographers,
Wedding Chapels,weddingchappels,
Wedding Planning,wedding_planning,
Financial Services,financialservices,
Banks & Credit Unions,banks,
Check Cashing/Pay-day Loans,paydayloans,
Currency Exchange,currencyexchange,
Debt Relief Services,debtrelief,
Financial Advising,financialadvising,
Insurance,insurance,
Auto Insurance,autoinsurance,
Home & Rental Insurance,homeinsurance,
Life Insurance,lifeinsurance,
Investing,investing,
Tax Services,taxservices,
Food,food,
Bagels,bagels,
Bakeries,bakeries,
Beer, Wine & Spirits,beer_and_wine,
Breweries,breweries,
Bubble Tea,bubbletea,
Butcher,butcher,
CSA,csa,
Cideries,cideries,
Coffee & Tea,coffee,
Convenience Stores,convenience,
Cupcakes,cupcakes,
Desserts,desserts,
Distilleries,distilleries,
Do-It-Yourself Food,diyfood,
Donuts,donuts,
Empanadas,empanadas,
Ethnic Grocery,ethnicgrocery,
Farmers Market,farmersmarket,
Food Delivery Services,fooddeliveryservices,
Food Trucks,foodtrucks,
Gelato,gelato,
Grocery,grocery,
Ice Cream & Frozen Yogurt,icecream,
Internet Cafes,internetcafe,
Juice Bars & Smoothies,juicebars,
Organic Stores,organic_stores,
Pretzels,pretzels,
Shaved Ice,shavedice,
Specialty Food,gourmet,
Candy Stores,candy,
Cheese Shops,cheese,
Chocolatiers & Shops,chocolate,
Ethnic Food,ethnicmarkets,
Fruits & Veggies,markets,
Health Markets,healthmarkets,
Herbs & Spices,herbsandspices,
Macarons,macarons,
Meat Shops,meats,
Pasta Shops,pastashops,
Popcorn Shops,popcorn,
Seafood Markets,seafoodmarkets,
Street Vendors,streetvendors,
Tea Rooms,tea,
Wineries,wineries,
Wine Tasting Room,winetastingroom,
Health & Medical,health,
Acupuncture,acupuncture,
Assisted Living Facilities,assistedliving,
Ayurveda,ayurveda,
Blood & Plasma Donation Centers,blooddonation,
Cannabis Clinics,cannabis_clinics,
Cannabis Tours,cannabistours,
Chiropractors,chiropractors,
Colonics,colonics,
Concierge Medicine,conciergemedicine,
Counseling & Mental Health,c_and_mh,
Psychologists,psychologists,
Sex Therapists,sextherapists,
Sports Psychologists,sportspsychologists,
Dentists,dentists,
Cosmetic Dentists,cosmeticdentists,
Endodontists,endodontists,
General Dentistry,generaldentistry,
Oral Surgeons,oralsurgeons,
Orthodontists,orthodontists,
Pediatric Dentists,pediatric_dentists,
Periodontists,periodontists,
Diagnostic Services,diagnosticservices,
Diagnostic Imaging,diagnosticimaging,
Laboratory Testing,laboratorytesting,
Dialysis Clinics,dialysisclinics,
Doctors,physicians,
Allergists,allergist,
Anesthesiologists,anesthesiologists,
Audiologist,audiologist,
Cardiologists,cardiology,
Cosmetic Surgeons,cosmeticsurgeons,
Dermatologists,dermatology,
Ear Nose & Throat,earnosethroat,
Endocrinologists,endocrinologists,
Family Practice,familydr,
Fertility,fertility,
Gastroenterologist,gastroenterologist,
Gerontologists,gerontologist,
Internal Medicine,internalmed,
Naturopathic/Holistic,naturopathic,
Nephrologists,nephrologists,
Neurologist,neurologist,
Obstetricians & Gynecologists,obgyn,
Oncologist,oncologist,
Ophthalmologists,opthamalogists,
Orthopedists,orthopedists,
Osteopathic Physicians,osteopathicphysicians,
Pediatricians,pediatricians,
Podiatrists,podiatrists,
Proctologists,proctologist,
Psychiatrists,psychiatrists,
Pulmonologist,pulmonologist,
Radiologists,radiologists,
Rheumatologists,rhematologists,
Spine Surgeons,spinesurgeons,
Sports Medicine,sportsmed,
Surgeons,surgeons,
Tattoo Removal,tattooremoval,
Urologists,urologists,
Doulas,doulas,
Emergency Rooms,emergencyrooms,
Habilitative Services,habilitativeservices,
Halotherapy,halotherapy,
Health Insurance Offices,healthinsurance,
Hearing Aid Providers,hearingaidproviders,
Home Health Care,homehealthcare,
Hospice,hospice,
Hospitals,hospitals,
Hypnosis/Hypnotherapy,hypnosis,
IV Hydration,ivhydration,
Lactation Services,lactationservices,
Laser Eye Surgery/Lasik,laserlasikeyes,
Lice Services,liceservices,
Massage Therapy,massage_therapy,
Medical Centers,medcenters,
Walk-in Clinics,walkinclinics,
Medical Spas,medicalspa,
Medical Transportation,medicaltransportation,
Midwives,midwives,
Nurse Practitioner,nursepractitioner,
Nutritionists,nutritionists,
Occupational Therapy,occupationaltherapy,
Optometrists,optometrists,
Orthotics,orthotics,
Oxygen Bars,oxygenbars,
Personal Care Services,personalcare,
Physical Therapy,physicaltherapy,
Placenta Encapsulations,placentaencapsulation,
Prenatal/Perinatal Care,prenatal,
Prosthetics,prosthetics,
Prosthodontists,prosthodontists,
Reflexology,reflexology,
Rehabilitation Center,rehabilitation_center,
Reiki,reiki,
Retirement Homes,retirement_homes,
Saunas,saunas,
Sleep Specialists,sleepspecialists,
Speech Therapists,speech_therapists,
Sperm Clinic,spermclinic,
Traditional Chinese Medicine,tcm,
Tui Na,tuina,
Urgent Care,urgent_care,
Weight Loss Centers,weightlosscenters,
Home Services,homeservices,
Building Supplies,buildingsupplies,
Cabinetry,cabinetry,
Carpenters,carpenters,
Carpet Installation,carpetinstallation,
Carpeting,carpeting,
Childproofing,childproofing,
Chimney Sweeps,chimneysweeps,
Contractors,contractors,
Countertop Installation,countertopinstall,
Damage Restoration,damagerestoration,
Decks & Railing,decksrailing,
Demolition Services,demolitionservices,
Door Sales/Installation,doorsales,
Drywall Installation & Repair,drywall,
Electricians,electricians,
Fences & Gates,fencesgates,
Fire Protection Services,fireprotection,
Fireplace Services,fireplace,
Firewood,firewood,
Flooring,flooring,
Furniture Assembly,furnitureassembly,
Garage Door Services,garage_door_services,
Gardeners,gardeners,
Glass & Mirrors,glassandmirrors,
Gutter Services,gutterservices,
Handyman,handyman,
Heating & Air Conditioning/HVAC,hvac,
Holiday Decorating Services,seasonaldecorservices,
Home Automation,homeautomation,
Home Cleaning,homecleaning,
Home Inspectors,home_inspectors,
Home Network Installation,homenetworkinstall,
Home Organization,home_organization,
Home Theatre Installation,hometheatreinstallation,
Home Window Tinting,homewindowtinting,
House Sitters,housesitters,
Insulation Installation,insulationinstallation,
Interior Design,interiordesign,
Internet Service Providers,isps,
Irrigation,irrigation,
Keys & Locksmiths,locksmiths,
Landscape Architects,landscapearchitects,
Landscaping,landscaping,
Lighting Fixtures & Equipment,lighting,
Masonry/Concrete,masonry_concrete,
Movers,movers,
Painters,painters,
Patio Coverings,patiocoverings,
Plumbing,plumbing,
Pool & Hot Tub Service,poolservice,
Pool Cleaners,poolcleaners,
Pressure Washers,pressurewashers,
Real Estate,realestate,
Apartments,apartments,
Art Space Rentals,artspacerentals,
Commercial Real Estate,commercialrealestate,
Estate Liquidation,estateliquidation,
Home Staging,homestaging,
Kitchen Incubators,kitchenincubators,
Mobile Home Dealers,mobilehomes,
Mobile Home Parks,mobileparks,
Mortgage Brokers,mortgagebrokers,
Property Management,propertymgmt,
Real Estate Agents,realestateagents,
Real Estate Services,realestatesvcs,
Shared Office Spaces,sharedofficespaces,
University Housing,university_housing,
Refinishing Services,refinishing,
Roof Inspectors,roofinspectors,
Roofing,roofing,
Security Systems,securitysystems,
Shades & Blinds,blinds,
Shutters,shutters,
Solar Installation,solarinstallation,
Structural Engineers,structuralengineers,
Stucco Services,stucco,
Television Service Providers,televisionserviceproviders,
Tiling,tiling,
Tree Services,treeservices,
Utilities,utilities,
Vinyl Siding,vinylsiding,
Water Heater Installation/Repair,waterheaterinstallrepair,
Water Purification Services,waterpurification,
Waterproofing,waterproofing,
Window Washing,windowwashing,
Windows Installation,windowsinstallation,
Hotels & Travel,hotelstravel,
Airports,airports,
Airport Terminals,airportterminals,
Bed & Breakfast,bedbreakfast,
Campgrounds,campgrounds,
Car Rental,carrental,
Guest Houses,guesthouses,
Health Retreats,healthretreats,
Hostels,hostels,
Hotels,hotels,
Mountain Huts,mountainhuts,
Rest Stops,reststops,
Motorcycle Rental,motorcycle_rental,
RV Parks,rvparks,
RV Rental,rvrental,
Resorts,resorts,
Ski Resorts,skiresorts,
Tours,tours,
Architectural Tours,architecturaltours,
Art Tours,arttours,
Bus Tours,bustours,
Food Tours,foodtours,
Historical Tours,historicaltours,
Walking Tours,walkingtours,
Wine Tours,winetours,
Train Stations,trainstations,
Transportation,transport,
Airlines,airlines,
Airport Shuttles,airport_shuttles,
Bike Sharing,bikesharing,
Buses,buses,
Cable Cars,cablecars,
Limos,limos,
Pedicabs,pedicabs,
Public Transportation,publictransport,
Taxis,taxis,
Trains,trains,
Travel Services,travelservices,
Vacation Rental Agents,vacationrentalagents,
Vacation Rentals,vacation_rentals,
Local Flavor,localflavor,
Unofficial Yelp Events,unofficialyelpevents,
Yelp Events,yelpevents,
Local Services,localservices,
3D Printing,3dprinting,
Adoption Services,adoptionservices,
Air Duct Cleaning,airductcleaning,
Appliances & Repair,homeappliancerepair,
Appraisal Services,appraisalservices,
Art Restoration,artrestoration,
Bail Bondsmen,bailbondsmen,
Bike Repair/Maintenance,bike_repair_maintenance,
Bookbinding,bookbinding,
Carpet Cleaning,carpet_cleaning,
Child Care & Day Care,childcare,
Clock Repair,clockrepair,
Community Gardens,communitygardens,
Community Service/Non-Profit,nonprofit,
Food Banks,foodbanks,
Couriers & Delivery Services,couriers,
Dry Cleaning & Laundry,drycleaninglaundry,
Elder Care Planning,eldercareplanning,
Electronics Repair,electronicsrepair,
Engraving,engraving,
Farm Equipment Repair,farmequipmentrepair,
Funeral Services & Cemeteries,funeralservices,
Furniture Rental,rentfurniture,
Furniture Repair,furniturerepair,
Furniture Reupholstery,reupholstery,
IT Services & Computer Repair,itservices,
Data Recovery,datarecovery,
Mobile Phone Repair,mobilephonerepair,
Telecommunications,telecommunications,
Jewelry Repair,jewelryrepair,
Junk Removal & Hauling,junkremovalandhauling,
Knife Sharpening,knifesharpening,
Machine & Tool Rental,machinerental,
Mailbox Centers,mailboxcenters,
Metal Fabricators,metalfabricators,
Musical Instrument Services,musicinstrumentservices,
Guitar Stores,guitarstores,
Piano Services,pianoservices,
Piano Stores,pianostores,
Nanny Services,nannys,
Notaries,notaries,
Pest Control,pest_control,
Powder Coating,powdercoating,
Printing Services,copyshops,
Propane,propane,
Recording & Rehearsal Studios,recording_studios,
Recycling Center,recyclingcenter,
Screen Printing,screenprinting,
Screen Printing/T-Shirt Printing,screen_printing_tshirt_printing,
Self Storage,selfstorage,
Septic Services,septicservices,
Sewing & Alterations,sewingalterations,
Shipping Centers,shipping_centers,
Shoe Repair,shoerepair,
Snow Removal,snowremoval,
Watch Repair,watch_repair,
Water Delivery,waterdelivery,
Well Drilling,welldrilling,
Mass Media,massmedia,
Print Media,printmedia,
Radio Stations,radiostations,
Television Stations,televisionstations,
Nightlife,nightlife,
Adult Entertainment,adultentertainment,
Bars,bars,
Airport Lounges,airportlounges,
Beer Bar,beerbar,
Champagne Bars,champagne_bars,
Cocktail Bars,cocktailbars,
Dive Bars,divebars,
Drive-Thru Bars,drivethrubars,
Gay Bars,gaybars,
Hookah Bars,hookah_bars,
Irish Pub,irish_pubs,
Lounges,lounges,
Pubs,pubs,
Sports Bars,sportsbars,
Wine Bars,wine_bars,
Beer Gardens,beergardens,
Comedy Clubs,comedyclubs,
Country Dance Halls,countrydancehalls,
Dance Clubs,danceclubs,
Jazz & Blues,jazzandblues,
Karaoke,karaoke,
Music Venues,musicvenues,
Piano Bars,pianobars,
Pool Halls,poolhalls,
Pets,pets,
Animal Shelters,animalshelters,
Horse Boarding,horse_boarding,
Pet Adoption,petadoption,
Pet Services,petservices,
Aquarium Services,aquariumservices,
Dog Walkers,dogwalkers,
Pet Boarding/Pet Sitting,pet_sitting,
Pet Breeders,petbreeders,
Pet Groomers,groomer,
Pet Training,pet_training,
Pet Stores,petstore,
Bird Shops,birdshops,
Local Fish Stores,localfishstores,
Reptile Shops,reptileshops,
Veterinarians,vet,
Professional Services,professional,
Accountants,accountants,
Advertising,advertising,
Architects,architects,
Boat Repair,boatrepair,
Business Consulting,businessconsulting,
Career Counseling,careercounseling,
Editorial Services,editorialservices,
Employment Agencies,employmentagencies,
Graphic Design,graphicdesign,
Internet Service Providers,isps,
Lawyers,lawyers,
Bankruptcy Law,bankruptcy,
Business Law,businesslawyers,
Contract Law,contractlaw,
Criminal Defense Law,criminaldefense,
DUI Law,duilawyers,
Divorce & Family Law,divorce,
Employment Law,employmentlawyers,
Entertainment Law,entertainmentlaw,
Estate Planning Law,estateplanning,
Wills, Trusts, & Probates,willstrustsprobates,
General Litigation,general_litigation,
IP & Internet Law,iplaw,
Immigration Law,immigrationlawyers,
Personal Injury Law,personal_injury,
Real Estate Law,realestatelawyers,
Tax Law,taxlaw,
Legal Services,legalservices,
Life Coach,lifecoach,
Marketing,marketing,
Matchmakers,matchmakers,
Mediators,mediators,
Music Production Services,musicproduction,
Office Cleaning,officecleaning,
Patent Law,patentlaw,
Payroll Services,payroll,
Personal Assistants,personalassistants,
Private Investigation,privateinvestigation,
Product Design,productdesign,
Public Relations,publicrelations,
Security Services,security,
Shredding Services,shredding,
Signmaking,signmaking,
Software Development,softwaredevelopment,
Talent Agencies,talentagencies,
Taxidermy,taxidermy,
Tenant and Eviction Law,tenantlaw,
Translation Services,translationservices,
Video/Film Production,videofilmproductions,
Web Design,web_design,
Public Services & Government,publicservicesgovt,
Community Centers,communitycenters,
Courthouses,courthouses,
Departments of Motor Vehicles,departmentsofmotorvehicles,
Embassy,embassy,
Fire Departments,firedepartments,
Landmarks & Historical Buildings,landmarks,
Libraries,libraries,
Police Departments,policedepartments,
Post Offices,postoffices,
Real Estate,realestate,
Apartments,apartments,
Art Space Rentals,artspacerentals,
Commercial Real Estate,commercialrealestate,
Estate Liquidation,estateliquidation,
Home Staging,homestaging,
Kitchen Incubators,kitchenincubators,
Mobile Home Dealers,mobilehomes,
Mobile Home Parks,mobileparks,
Mortgage Brokers,mortgagebrokers,
Property Management,propertymgmt,
Real Estate Agents,realestateagents,
Real Estate Services,realestatesvcs,
Shared Office Spaces,sharedofficespaces,
University Housing,university_housing,
Religious Organizations,religiousorgs,
Buddhist Temples,buddhist_temples,
Churches,churches,
Hindu Temples,hindu_temples,
Mosques,mosques,
Synagogues,synagogues,
Restaurants,restaurants,
Afghan,afghani,
African,african,
Senegalese,senegalese,
South African,southafrican,
American (New),newamerican,
American (Traditional),tradamerican,
Arabian,arabian,
Argentine,argentine,
Armenian,armenian,
Asian Fusion,asianfusion,
Australian,australian,
Austrian,austrian,
Bangladeshi,bangladeshi,
Barbeque,bbq,
Basque,basque,
Belgian,belgian,
Brasseries,brasseries,
Brazilian,brazilian,
Breakfast & Brunch,breakfast_brunch,
British,british,
Buffets,buffets,
Burgers,burgers,
Burmese,burmese,
Cafes,cafes,
Cafeteria,cafeteria,
Cajun/Creole,cajun,
Cambodian,cambodian,
Caribbean,caribbean,
Dominican,dominican,
Haitian,haitian,
Puerto Rican,puertorican,
Trinidadian,trinidadian,
Catalan,catalan,
Cheesesteaks,cheesesteaks,
Chicken Shop,chickenshop,
Chicken Wings,chicken_wings,
Chinese,chinese,
Cantonese,cantonese,
Dim Sum,dimsum,
Shanghainese,shanghainese,
Szechuan,szechuan,
Comfort Food,comfortfood,
Creperies,creperies,
Cuban,cuban,
Czech,czech,
Delis,delis,
Diners,diners,
Ethiopian,ethiopian,
Fast Food,hotdogs,
Filipino,filipino,
Fish & Chips,fishnchips,
Fondue,fondue,
Food Court,food_court,
Food Stands,foodstands,
French,french,
Gastropubs,gastropubs,
German,german,
Gluten-Free,gluten_free,
Greek,greek,
Halal,halal,
Hawaiian,hawaiian,
Himalayan/Nepalese,himalayan,
Hot Dogs,hotdog,
Hot Pot,hotpot,
Hungarian,hungarian,
Iberian,iberian,
Indian,indpak,
Indonesian,indonesian,
Irish,irish,
Italian,italian,
Calabrian,calabrian,
Sardinian,sardinian,
Tuscan,tuscan,
Japanese,japanese,
Ramen,ramen,
Teppanyaki,teppanyaki,
Korean,korean,
Kosher,kosher,
Laotian,laotian,
Latin American,latin,
Colombian,colombian,
Salvadoran,salvadoran,
Venezuelan,venezuelan,
Live/Raw Food,raw_food,
Malaysian,malaysian,
Mediterranean,mediterranean,
Falafel,falafel,
Mexican,mexican,
Middle Eastern,mideastern,
Egyptian,egyptian,
Lebanese,lebanese,
Modern European,modern_european,
Mongolian,mongolian,
Moroccan,moroccan,
Pakistani,pakistani,
Persian/Iranian,persian,
Peruvian,peruvian,
Pizza,pizza,
Polish,polish,
Portuguese,portuguese,
Poutineries,poutineries,
Russian,russian,
Salad,salad,
Sandwiches,sandwiches,
Scandinavian,scandinavian,
Scottish,scottish,
Seafood,seafood,
Singaporean,singaporean,
Slovakian,slovakian,
Soul Food,soulfood,
Soup,soup,
Southern,southern,
Spanish,spanish,
Sri Lankan,srilankan,
Steakhouses,steak,
Supper Clubs,supperclubs,
Sushi Bars,sushi,
Syrian,syrian,
Taiwanese,taiwanese,
Tapas Bars,tapas,
Tapas/Small Plates,tapasmallplates,
Tex-Mex,tex-mex,
Thai,thai,
Turkish,turkish,
Ukrainian,ukrainian,
Uzbek,uzbek,
Vegan,vegan,
Vegetarian,vegetarian,
Vietnamese,vietnamese,
Shopping,shopping,
Adult,adult,
Antiques,antiques,
Art Galleries,galleries,
Arts & Crafts,artsandcrafts,
Art Supplies,artsupplies,
Cards & Stationery,stationery,
Cooking Classes,cookingclasses,
Costumes,costumes,
Embroidery & Crochet,embroideryandcrochet,
Fabric Stores,fabricstores,
Framing,framing,
Auction Houses,auctionhouses,
Baby Gear & Furniture,baby_gear,
Battery Stores,batterystores,
Bespoke Clothing,bespoke,
Books, Mags, Music & Video,media,
Bookstores,bookstores,
Comic Books,comicbooks,
Music & DVDs,musicvideo,
Newspapers & Magazines,mags,
Video Game Stores,videogamestores,
Videos & Video Game Rental,videoandgames,
Vinyl Records,vinyl_records,
Brewing Supplies,brewingsupplies,
Bridal,bridal,
Computers,computers,
Cosmetics & Beauty Supply,cosmetics,
Customized Merchandise,custommerchandise,
Department Stores,deptstores,
Discount Store,discountstore,
Drugstores,drugstores,
Duty-Free Shops,dutyfreeshops,
Electronics,electronics,
Eyewear & Opticians,opticians,
Farming Equipment,farmingequipment,
Fashion,fashion,
Accessories,accessories,
Children's Clothing,childcloth,
Clothing Rental,clothingrental,
Department Stores,deptstores,
Formal Wear,formalwear,
Hats,hats,
Leather Goods,leather,
Lingerie,lingerie,
Maternity Wear,maternity,
Men's Clothing,menscloth,
Plus Size Fashion,plus_size_fashion,
Shoe Stores,shoes,
Sports Wear,sportswear,
Surf Shop,surfshop,
Swimwear,swimwear,
Used, Vintage & Consignment,vintage,
Women's Clothing,womenscloth,
Fireworks,fireworks,
Fitness/Exercise Equipment,fitnessequipment,
Flea Markets,fleamarkets,
Flowers & Gifts,flowers,
Cards & Stationery,stationery,
Florists,florists,
Gift Shops,giftshops,
Gold Buyers,goldbuyers,
Golf Equipment Shops,golfshops,
Guns & Ammo,guns_and_ammo,
Head Shops,headshops,
High Fidelity Audio Equipment,hifi,
Hobby Shops,hobbyshops,
Home & Garden,homeandgarden,
Appliances,appliances,
Christmas Trees,christmastrees,
Furniture Stores,furniture,
Hardware Stores,hardware,
Holiday Decorations,holidaydecorations,
Home Decor,homedecor,
Hot Tub & Pool,hottubandpool,
Kitchen & Bath,kitchenandbath,
Mattresses,mattresses,
Nurseries & Gardening,gardening,
Outdoor Furniture Stores,outdoorfurniture,
Paint Stores,paintstores,
Pumpkin Patches,pumpkinpatches,
Rugs,rugs,
Horse Equipment Shops,horsequipment,
Jewelry,jewelry,
Knitting Supplies,knittingsupplies,
Livestock Feed & Supply,livestocksupply,
Luggage,luggage,
Medical Supplies,medicalsupplies,
Mobile Phone Accessories,cellphoneaccessories,
Mobile Phones,mobilephones,
Motorcycle Gear,motorcyclinggear,
Musical Instruments & Teachers,musicalinstrumentsandteachers,
Office Equipment,officeequipment,
Outlet Stores,outlet_stores,
Pawn Shops,pawn,
Personal Shopping,personal_shopping,
Photography Stores & Services,photographystores,
Pool & Billiards,poolbilliards,
Pop-up Shops,popupshops,
Shopping Centers,shoppingcenters,
Souvenir Shops,souvenirs,
Spiritual Shop,spiritual_shop,
Sporting Goods,sportgoods,
Bikes,bikes,
Dive Shops,diveshops,
Golf Equipment,golfequipment,
Outdoor Gear,outdoorgear,
Skate Shops,skateshops,
Ski & Snowboard Shops,skishops,
Sports Wear,sportswear,
Tabletop Games,tabletopgames,
Thrift Stores,thrift_stores,
Tobacco Shops,tobaccoshops,
Toy Stores,toys,
Trophy Shops,trophyshops,
Uniforms,uniforms,
Used Bookstore,usedbooks,
Vape Shops,vapeshops,
Vitamins & Supplements,vitaminssupplements,
Watches,watches,
Wholesale Stores,wholesale_stores,
Wigs,wigs,";
    }
}
